name: infotainment_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  lucide_icons: ^0.257.0
  just_audio: ^0.9.36
  audio_session: ^0.1.13
  provider: ^6.0.5
  file_picker: ^10.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  external_path: ^2.2.0
  shared_preferences: ^2.2.2
  ionicons: ^0.2.2
  marquee: ^2.2.3
  audio_waveforms: ^1.0.5
  dio: ^5.4.0
  thermal: ^1.1.11
  flutter_volume_controller: ^1.3.3
  audio_metadata_reader: ^1.4.2
  hugeicons: ^0.0.11
  google_maps_flutter: ^2.6.0
  http: ^0.13.6
  flutter_tts: ^3.8.5
  location: ^8.0.1
  google_places_flutter: ^2.0.6
  package_rename: ^1.10.0
  rename_app: ^1.6.5
  change_app_package_name: ^1.5.0
  fl_chart: ^0.66.0
  weather_icons: ^3.0.0
  weather_animation: ^1.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/album_placeholder.jpg
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
    - family: SFPRO
      fonts:
        - asset: assets/fonts/SFPRO/SFPRO_REGULAR.otf
